from playwright.sync_api import sync_playwright
from pathlib import Path
import os,json
out=Path(os.environ['STRIVE_PROOF_DIR']);base=os.environ['STRIVE_PREVIEW_URL'];assert base.startswith('http://127.0.0.1:')
with sync_playwright() as p:
 b=p.chromium.launch();c=b.new_context(viewport={'width':390,'height':844});c.route('**/*',lambda r:r.continue_() if r.request.url.startswith('http://127.0.0.1:') else r.abort());page=c.new_page();page.goto(base);page.evaluate("sessionStorage.setItem('fixture-signed-out','1')");page.reload();page.get_by_role('button',name='Feedback',exact=True).click();page.get_by_label('Your feedback').fill('TEST DATA anonymous draft');page.get_by_role('button',name='Sign in to send feedback',exact=True).click();page.get_by_text('Your draft is ready. Review it, then send.',exact=True).wait_for();assert page.get_by_label('Your feedback').input_value()=='TEST DATA anonymous draft';assert page.request.get(base+'/proof').json()==[];page.screenshot(path=str(out/'mobile-login-draft.png'))
 def lost(r):
  r.fetch();r.abort();page.unroute('**/rpc/save_feedback',lost)
 page.route('**/rpc/save_feedback',lost);page.get_by_role('button',name='Send feedback',exact=True).click();page.get_by_text('Could not confirm the save. Your text is still here. Try again.',exact=True).wait_for();page.get_by_label('Your feedback').fill('TEST DATA revised after lost response');page.get_by_role('button',name='Send as new feedback',exact=True).wait_for();page.screenshot(path=str(out/'mobile-edited-retry.png'));page.get_by_role('button',name='Send as new feedback',exact=True).click();page.get_by_text('Saved. Thanks for saying it.',exact=True).wait_for();rows=page.request.get(base+'/proof').json();assert len(rows)==2;assert {r['message'] for r in rows}=={'TEST DATA anonymous draft','TEST DATA revised after lost response'};assert len({r['request_id'] for r in rows})==2;page.reload();assert page.request.get(base+'/proof').json()==rows
 result={'fixture_login_reload_draft_preserved':True,'auto_submissions_after_login':0,'edited_after_commit_lost_response':'explicit new-message button; both exact payloads persisted','persisted_rows':rows,'actual_OAuth':False,'surface':'shipped feedback module with disposable PostgreSQL RPC, fixture sign-in reload'};(out/'login-edit-browser-results.json').write_text(json.dumps(result,indent=2));print(json.dumps(result));b.close()
